name: CI

on:
  push:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Typescript
        run: npm run lint:ts

      - name: ESlint
        run: npm run lint

      - name: SCSS lint
        run: npm run lint:scss

      - name: Unit tests
        run: npm run test:unit

      - name: Validate Chromatic token
        run: |
          if [ -z "${{ secrets.CHROMATIC_PROJECT_TOKEN }}" ]; then
            echo "CHROMATIC_PROJECT_TOKEN is missing in repository secrets"
            exit 1
          fi

      - name: Regression tests
        run: npm run test:regression -- --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --exit-zero-on-changes

      - name: Build
        run: npm run build
